version: '3.1'

services:
  nextjs:
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /opt/app/node_modules
      - /opt/app/.next
    restart: always